## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    username: root
    password: "Sankha@12"
    url: jdbc:mysql://localhost:3306/project_db
    platform: mysql
    
    
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: sankhamondal400@gmail.com
    password: yeavsfxkkebfxzgf
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false



  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?
server:
  servlet:
    contextPath: /api

jwtSecret: me.zhulin
jwtExpiration: 86400
